function [] = SetFigureDefaults(size_x, size_y)
set(groot, 'DefaultLineLineWidth', 2, ...
           'DefaultTextInterpreter', 'LaTeX', ...
           'DefaultAxesTickLabelInterpreter', 'LaTeX', ...
           'DefaultAxesFontName', 'LaTeX', ...
           'DefaultLegendInterpreter', 'LaTeX', ...
           'DefaultAxesLineWidth', 1.5, ...
           'DefaultAxesFontSize', 20, ...
           'DefaultAxesBox', 'on', ...
           'DefaultAxesColor', [1, 1, 1], ...
           'DefaultFigureColor', [1, 1, 1], ...
           'DefaultFigureInvertHardcopy', 'off', ...
           'DefaultFigurePaperUnits', 'inches', ...
           'DefaultFigureUnits', 'inches', ...
           'DefaultFigurePaperPositionMode', 'auto', ...
           'DefaultFigurePosition', [5.0, 1.0, size_x, size_y]);
end

% % % % % % % % % % % % % % % Default command % % % % % % % % % % % % % % %
% set(groot, 'DefaultLineLineWidth', 3, ...
%            'DefaultTextInterpreter', 'LaTeX', ...
%            'DefaultAxesTickLabelInterpreter', 'LaTeX', ...
%            'DefaultAxesFontName', 'LaTeX', ...
%            'DefaultLegendInterpreter', 'LaTeX', ...
%            'DefaultAxesLineWidth', 1.5, ...
%            'DefaultAxesFontSize', 16, ...
%            'DefaultAxesBox', 'on', ...
%            'DefaultAxesColor', [1, 1, 1], ...
%            'DefaultFigureColor', [1, 1, 1], ...
%            'DefaultFigureInvertHardcopy', 'off', ...
%            'DefaultFigurePaperUnits', 'inches', ...
%            'DefaultFigureUnits', 'inches', ...
%            'DefaultFigurePaperPosition', [0, 0, 5, 3.09], ...
%            'DefaultFigurePaperSize', [5, 3.09], ...
%            'DefaultFigurePosition', [0.1, 0.1, 4.9, 2.99]);
